version: '3.8'

services:
  postgresql-jotrack:
    image: postgres:16-alpine
    container_name: postgresql-jotrack
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresql-jotrack
    restart: unless-stopped

networks:
  jotrack-local:
