### variables
@hostname=localhost
@port=8000

@userId=
@jobId=1
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzA2MjQ0MTY3LCJleHAiOjE3MDY4NDg5Njd9.c7kXNA4mLo8fNpanVAGIo9YGca7KRkjKLwVgvogKmBQ

### signup user

POST http://{{hostname}}:{{port}}/api/auth/signup HTTP/1.1
Content-Type: application/json

{
  "email": "email@domain.com",
  "password": "password",
  "role": "user",
  "firstName": "firstName",
  "lastName": "lastName",
  "phoneNumber": 1234567890 
}

### login user

POST http://{{hostname}}:{{port}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "email@domain.com",
  "password": "password"
}

### retrieves users

GET http://{{hostname}}:{{port}}/api/users HTTP/1.1

### updates user

PUT http://{{hostname}}:{{port}}/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{access_token}}

### removes user

DELETE http://{{hostname}}:{{port}}/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{access_token}}

### chnage password

PUT http://{{hostname}}:{{port}}/api/users HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "password": "updatedPassword"
}

### retrieves jobs
# @Param() filter: string;
#   - dateTime

GET http://{{hostname}}:{{port}}/api/jobs HTTP/1.1

### creates job

POST http://{{hostname}}:{{port}}/api/jobs HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "title",
  "description": "description",
  "companyName": "companyName",
  "position": "position",
  "requirements": "requirements",
  "postalCode":"A1A 1A1",
  "street": "23 Some Street",
  "city": "Toronto",
  "province":"Ontario",
  "country": "Canada"
}

### update job

PUT http://{{hostname}}:{{port}}/api/jobs/{{jobId}} HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "updatedTitle",
  "description": "updatedDescription",
  "companyName": "updatedCompanyName",
  "position": "position",
  "requirements": "requirements",
  "postalCode":"A1A 1A1",
  "street": "23 Some Street",
  "city": "Toronto",
  "province":"Ontario",
  "country": "Canada"
}

### delete job

DELETE http://{{hostname}}:{{port}}/api/jobs/{{jobId}} HTTP/1.1
Authorization: Bearer {{access_token}}

### apply for a job

POST http://{{hostname}}:{{port}}/api/job-applications/{{jobId}}
Authorization: Bearer {{access_token}}

### retrieve job applications

GET http://{{hostname}}:{{port}}/api/job-applications

### retrieve own job applications

GET http://{{hostname}}:{{port}}/api/job-applications/applications
