### variables
@hostname=localhost
@port=8000

@userId=
@jobId=
@access_token=

### create user

POST http://{{hostname}}:{{port}}/api/auth/signup HTTP/1.1
Content-Type: application/json

{
  "email": "email@domain.com",
  "password": "password",
  "role": "user",
  "firstName": "firstName",
  "lastName": "lastName"
}

### log-in user

POST http://{{hostname}}:{{port}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "email@domain.com",
  "password": "password"
}

### retrieves users

GET http://{{hostname}}:{{port}}/api/users HTTP/1.1

### create user

PUT http://{{hostname}}:{{port}}/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{access_token}}

### removes user

DELETE http://{{hostname}}:{{port}}/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{access_token}}

### retrieves jobs

GET http://{{hostname}}:{{port}}/api/jobs HTTP/1.1

### creates job

POST http://{{hostname}}:{{port}}/api/jobs HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "title",
  "description": "description",
  "companyName": "companyName"
}

### update job

PUT http://{{hostname}}:{{port}}/api/jobs/{{jobId}} HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "updatedTitle",
  "description": "updatedDescription",
  "companyName": "updatedCompanyName"
}

### delete job

DELETE http://{{hostname}}:{{port}}/api/jobs/{{jobId}} HTTP/1.1
Authorization: Bearer {{access_token}}

###
